# k8s/v1-1/service.yaml
#
# ClusterIP Service for the v1.1 deployment.
#
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-svc
  namespace: catalogue-v1-1
  labels:
    app: product-catalogue
    version: v1.1
spec:
  type: ClusterIP
  selector:
    app: product-catalogue
    version: v1.1
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
